{
 "title": "Fare amount quatile by days",
 "time": { "from": "2023-03-01T00:00:00.000Z", "to": "2023-03-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "Missings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare amount quatile by days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT MAX(fare_amount_quantile), \"timestamp\" FROM dummy_metrics GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  }
 ]
}